apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: namespaceconfigs.redhat-cop.redhat.io
spec:
  group: redhat-cop.redhat.io
  names:
    kind: NamespaceConfig
    listKind: NamespaceConfigList
    plural: namespaceconfigs
    singular: namespaceconfig
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
