name: Build and Test

on:
  push:
    branches: [ master, add-github-workflow ]
  pull_request:
    branches: [ master, add-github-workflow ]

jobs:
  test:
    runs-on: [ubuntu-18.04]
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Install docker
      run: |
        sudo apt-get update
        sudo apt-get -y install docker.io

    - uses: actions/checkout@v2

    - name: Latest Deploy
      run: make gh-actions-latest-deploy

    - name: Release Deploy
      run: make gh-actions-release-deploy
